GCP cluster
shahargalon/book-store pull request #12
Opened 2020-11-03 22:22 UTC by shahargalon

2020-11-05 23:50 UTC, shahargalon commented
Hi @nirgn975 

I had done all this things and it work, you can try to  GET from book-store.shahargn.com
![image](https://user-images.githubusercontent.com/55717508/98308824-ab730580-1fd1-11eb-8ee5-22cfcbb0ce2c.png)

also I put on the deployment file on the image key some string ("IMGAE_VAR"),  that afterwards on the cloudbuild I change it with sed command to the right image (with the updated SHA). it work very nice, I wondering if you also do somthing like that on your cluster..

2020-11-06 00:11 UTC, nirgn975 requested changes

2020-11-06 00:11 UTC, nirgn975 commented on cloudbuild.yml
> +- name: ubuntu
You don't need this step.

2020-11-06 00:11 UTC, nirgn975 commented on k8s/book-store-deployment.yaml
> +        image: IMAGE_VAR
You can just construct the string right here, you have all the environment variables you need (I think, I read it in the docs).
`image: IMAGE_VAR` -> `image: gcr.io/$PROJECT_ID/book-store:$SHORT_SHA`.

2020-11-06 15:55 UTC, shahargalon commented on cloudbuild.yml
> +- name: ubuntu
I didnt change ot in the end..

2020-11-06 21:08 UTC, nirgn975 approved these changes

2020-11-06 21:13 UTC, merged